/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2020-11-14: 10h:39m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.4.1/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_local.sats: 158(line=10, offs=1) -- 202(line=12, offs=3)
*/

#include "source/SDL2/SDL_local.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_mixer.sats: 72(line=7, offs=1) -- 116(line=9, offs=3)
*/

#include "source/SDL2/SDL_mixer.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_net.sats: 33(line=7, offs=1) -- 75(line=9, offs=3)
*/

#include "source/SDL2/SDL_net.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_opengl.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_opengl.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_rwops.sats: 35(line=7, offs=1) -- 79(line=9, offs=3)
*/

#include "source/SDL2/SDL_rwops.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_thread.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_thread.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_local.sats: 158(line=10, offs=1) -- 202(line=12, offs=3)
*/

#include "source/SDL2/SDL_local.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_mixer.sats: 72(line=7, offs=1) -- 116(line=9, offs=3)
*/

#include "source/SDL2/SDL_mixer.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_net.sats: 33(line=7, offs=1) -- 75(line=9, offs=3)
*/

#include "source/SDL2/SDL_net.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_opengl.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_opengl.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_rwops.sats: 35(line=7, offs=1) -- 79(line=9, offs=3)
*/

#include "source/SDL2/SDL_rwops.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_thread.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_thread.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_local.sats: 158(line=10, offs=1) -- 202(line=12, offs=3)
*/

#include "source/SDL2/SDL_local.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_mixer.sats: 72(line=7, offs=1) -- 116(line=9, offs=3)
*/

#include "source/SDL2/SDL_mixer.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_net.sats: 33(line=7, offs=1) -- 75(line=9, offs=3)
*/

#include "source/SDL2/SDL_net.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_opengl.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_opengl.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_rwops.sats: 35(line=7, offs=1) -- 79(line=9, offs=3)
*/

#include "source/SDL2/SDL_rwops.cats"
/*
/home/tmj90/Goldelish-Engine/source/SDL2/SDL_thread.sats: 36(line=7, offs=1) -- 81(line=9, offs=3)
*/

#include "source/SDL2/SDL_thread.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
fpath atslab__path ;
atstkind_type(atstype_ptrk) atslab__x ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
atstkind_type(atstype_ptrk) atslab__path ;
atstkind_type(atstype_ptrk) atslab__x ;
} postiats_tyrec_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__map_fullpath, (atsrefarg0_type(fpath)), fpath) ;
ATSdyncst_mac(gldlsh_sdl_bind_SDL_RWFromFile)
ATSdyncst_extfun(_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_engine_056_sats__fpath_string, (fpath), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_ptr0_isnot_null)
ATSdyncst_mac(atspre_ptr_free)
ATSdyncst_extfun(_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_engine_056_sats__fpath_delete, (fpath), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 445(line=24, offs=1) -- 534(line=24, offs=90)
*/
ATSassume(_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl) ;
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__file_exists(atsrefarg0_type(fpath)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_get__1(atsrefarg0_type(fpath)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
postiats_tyrec_0
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_new__2(fpath) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
fpath
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_path__3(atsrefarg0_type(postiats_tyrec_0)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_asset__4(atsrefarg0_type(postiats_tyrec_0)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_path__5(atsrefarg1_type(postiats_tyrec_0), fpath) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_asset__6(atsrefarg1_type(postiats_tyrec_0), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 210(line=13, offs=21) -- 377(line=19, offs=4)
*/
/*
local: 
global: file_exists$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__file_exists(atsrefarg0_type(fpath) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp1, fpath) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 198(line=13, offs=9) -- 377(line=19, offs=4)
*/
#line 13 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_file_exists):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 225(line=13, offs=36) -- 377(line=19, offs=4)
*/
#line 13 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 244(line=14, offs=16) -- 265(line=14, offs=37)
*/
#line 14 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp1, _057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__map_fullpath(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 295(line=15, offs=29) -- 314(line=15, offs=48)
*/
#line 15 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp3, _057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_engine_056_sats__fpath_string(tmp1)) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 280(line=15, offs=14) -- 321(line=15, offs=55)
*/
#line 15 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp2, gldlsh_sdl_bind_SDL_RWFromFile(tmp3, ATSPMVstring("r"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 330(line=17, offs=6) -- 349(line=17, offs=25)
*/
#line 17 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp4, atspre_ptr0_isnot_null(tmp2)) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 327(line=17, offs=3) -- 373(line=18, offs=13)
*/
#line 17 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSif(
tmp4
) ATSthen() {
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 356(line=17, offs=32) -- 360(line=17, offs=36)
*/
#line 17 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 368(line=18, offs=8) -- 373(line=18, offs=13)
*/
#line 18 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 225(line=13, offs=36) -- 377(line=19, offs=4)
*/
#line 13 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__file_exists] */

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 400(line=21, offs=22) -- 436(line=21, offs=58)
*/
/*
local: 
global: asset_get$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8715)
tmparg = S2Evar(a(8715))
tmpsub = None()
*/
atstyvar_type(a)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_get__1(atsrefarg0_type(fpath) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 390(line=21, offs=12) -- 437(line=21, offs=59)
*/
#line 21 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_get):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 415(line=21, offs=37) -- 436(line=21, offs=58)
*/
#line 21 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmpret5, PMVtmpltcst(file_load<S2Evar(a(8715))>)(ATSPMVrefarg0(arg0))) ;

ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_get__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 565(line=27, offs=27) -- 735(line=32, offs=4)
*/
/*
local: 
global: asset_hndl_new$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8718)
tmparg = S2Evar(a(8718))
tmpsub = None()
*/
postiats_tyrec_0
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_new__2(fpath arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, postiats_tyrec_0) ;
ATStmpdec(tmp7, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp8, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 550(line=27, offs=12) -- 735(line=32, offs=4)
*/
#line 27 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_hndl_new):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 580(line=27, offs=42) -- 735(line=32, offs=4)
*/
#line 27 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 614(line=28, offs=31) -- 628(line=28, offs=45)
*/
#line 28 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp7, PMVtmpltcst(ptr_alloc<S2Evar(a(8718))>)()) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 651(line=29, offs=23) -- 669(line=29, offs=41)
*/
#line 29 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp8, PMVtmpltcst(asset_get<S2Evar(a(8718))>)(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 639(line=29, offs=11) -- 669(line=29, offs=41)
*/
#line 29 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSstore(ATSderef(tmp7, atstyvar_type(a)), tmp8) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 675(line=31, offs=2) -- 717(line=31, offs=44)
*/
#line 31 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret6, postiats_tyrec_0, atslab__path, arg0) ;
ATSINSstore_fltrec_ofs(tmpret6, postiats_tyrec_0, atslab__x, tmp7) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 580(line=27, offs=42) -- 735(line=32, offs=4)
*/
#line 27 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret6) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_new__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 768(line=34, offs=32) -- 784(line=34, offs=48)
*/
/*
local: 
global: asset_hndl_get_path$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8719)
tmparg = S2Evar(a(8719))
tmpsub = None()
*/
fpath
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_path__3(atsrefarg0_type(postiats_tyrec_0) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, fpath) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 748(line=34, offs=12) -- 784(line=34, offs=48)
*/
#line 34 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_hndl_get_path):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 777(line=34, offs=41) -- 784(line=34, offs=48)
*/
#line 34 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmpret9, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__path)) ;
ATSfunbody_end()
ATSreturn(tmpret9) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_path__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 818(line=36, offs=33) -- 920(line=42, offs=4)
*/
/*
local: 
global: asset_hndl_get_asset$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8721)
tmparg = S2Evar(a(8721))
tmpsub = None()
*/
atstyvar_type(a)
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_asset__4(atsrefarg0_type(postiats_tyrec_0) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstyvar_type(a)) ;
ATStmpdec(tmp11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstyvar_type(a)) ;
// ATStmpdec_void(tmp13) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 797(line=36, offs=12) -- 920(line=42, offs=4)
*/
#line 36 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_hndl_get_asset):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 827(line=36, offs=42) -- 920(line=42, offs=4)
*/
#line 36 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 850(line=37, offs=20) -- 851(line=37, offs=21)
*/
#line 37 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp11, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__x)) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 871(line=38, offs=12) -- 873(line=38, offs=14)
*/
#line 38 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp12, ATSderef(tmp11, atstyvar_type(a))) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 884(line=39, offs=11) -- 908(line=39, offs=35)
*/
#line 39 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove_void(tmp13, atspre_ptr_free(tmp11)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 913(line=41, offs=2) -- 916(line=41, offs=5)
*/
#line 41 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmpret10, tmp12) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 827(line=36, offs=42) -- 920(line=42, offs=4)
*/
#line 36 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_get_asset__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 953(line=44, offs=32) -- 1023(line=48, offs=4)
*/
/*
local: 
global: asset_hndl_set_path$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8723)
tmparg = S2Evar(a(8723))
tmpsub = None()
*/
atsvoid_t0ype
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_path__5(atsrefarg1_type(postiats_tyrec_0) arg0, fpath arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret14) ;
// ATStmpdec_void(tmp15) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 933(line=44, offs=12) -- 1023(line=48, offs=4)
*/
#line 44 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_hndl_set_path):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 975(line=45, offs=2) -- 996(line=45, offs=23)
*/
#line 45 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove_void(tmp15, _057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_engine_056_sats__fpath_delete(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab__path))) ;

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 999(line=46, offs=2) -- 1014(line=46, offs=17)
*/
#line 46 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSstore(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_1), postiats_tyrec_1, atslab__path), arg1) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 999(line=46, offs=2) -- 1014(line=46, offs=17)
*/
#line 46 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove_void(tmpret14, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret14) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_path__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/tmj90/Goldelish-Engine/source/g_asset.dats: 1057(line=50, offs=33) -- 1161(line=55, offs=4)
*/
/*
local: 
global: asset_hndl_set_asset$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8724)
tmparg = S2Evar(a(8724))
tmpsub = None()
*/
atsvoid_t0ype
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_asset__6(atsrefarg1_type(postiats_tyrec_0) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret16) ;
ATStmpdec(tmp17, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1036(line=50, offs=12) -- 1161(line=55, offs=4)
*/
#line 50 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSflab(__patsflab_asset_hndl_set_asset):
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1069(line=50, offs=45) -- 1161(line=55, offs=4)
*/
#line 50 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1097(line=51, offs=25) -- 1101(line=51, offs=29)
*/
#line 51 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove(tmp17, ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab__x)) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1112(line=52, offs=11) -- 1119(line=52, offs=18)
*/
#line 52 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSstore(ATSderef(tmp17, atstyvar_type(a)), arg1) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1130(line=53, offs=11) -- 1154(line=53, offs=35)
*/
#line 53 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSstore(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab__x), tmp17) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1130(line=53, offs=11) -- 1154(line=53, offs=35)
*/
#line 53 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
ATSINSmove_void(tmpret16, ATSPMVempty()) ;
/*
emit_instr: loc0 = /home/tmj90/Goldelish-Engine/source/g_asset.dats: 1069(line=50, offs=45) -- 1161(line=55, offs=4)
*/
#line 50 "/home/tmj90/Goldelish-Engine/source/g_asset.dats"
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret16) ;
} /* end of [_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_sats__asset_hndl_set_asset__6] */
#endif // end of [TEMPLATE]

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_tmj90_057_Goldelish_055_Engine_057_source_057_g_asset_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
